"use server";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
const ORG_ID = process.env.NEXT_PUBLIC_DEFAULT_ORG_ID!;
export type WhitelistEntry={id:string;pattern:string;kind:string;notes:string|null;is_active:boolean;created_at:string};
export type UnregisteredDomain={domain:string;party_names:string;contact_count:number};
export async function listWhitelist(){const sb=await createSupabaseServerClient();const{data}=await sb.rpc("list_email_whitelist",{p_org_id:ORG_ID});return(data||[]) as WhitelistEntry[]}
export async function getUnregisteredDomains(){const sb=await createSupabaseServerClient();const{data}=await sb.rpc("get_unregistered_party_domains",{p_org_id:ORG_ID});return(data||[]) as UnregisteredDomain[]}
export async function addWhitelistEntry(pattern:string,kind:"domain"|"address",notes:string):Promise<{ok:boolean;error?:string}>{const p=pattern.trim().toLowerCase();if(!p)return{ok:false,error:"empty"};if(kind==="domain"&&p.includes("@"))return{ok:false,error:"도메인은 @ 없이 입력하세요"};if(kind==="address"&&!p.includes("@"))return{ok:false,error:"주소는 @ 포함해서 입력하세요"};const sb=await createSupabaseServerClient();const{error}=await sb.rpc("add_email_whitelist",{p_org_id:ORG_ID,p_pattern:p,p_kind:kind,p_notes:notes||null});if(error)return{ok:false,error:error.message};revalidatePath("/settings/email-whitelist");return{ok:true}}
export async function bulkAddDomains(domains:Array<{domain:string;notes:string}>):Promise<{ok:boolean;added:number}>{const sb=await createSupabaseServerClient();let added=0;for(const{domain,notes}of domains){const{error}=await sb.rpc("add_email_whitelist",{p_org_id:ORG_ID,p_pattern:domain.toLowerCase().trim(),p_kind:"domain",p_notes:notes||null});if(!error)added++}revalidatePath("/settings/email-whitelist");return{ok:true,added}}
export async function toggleWhitelistEntry(id:string,active:boolean){const sb=await createSupabaseServerClient();await sb.rpc("toggle_email_whitelist",{p_id:id,p_active:active});revalidatePath("/settings/email-whitelist");return{ok:true}}
export async function deleteWhitelistEntry(id:string){const sb=await createSupabaseServerClient();await sb.rpc("delete_email_whitelist",{p_id:id});revalidatePath("/settings/email-whitelist");return{ok:true}}