-- ============================================================
-- fix_ctan_round_100k.sql
-- Founder decision 2026-07-09: this angel round raises
-- 100,000 USD only, dedicated to the US tissue validation test.
-- Not a 1,000,000 USD round with a first close.
--
-- CONSEQUENCE THAT MATTERS: the 500,000 USD patent transfer
-- consideration cannot be a use of these proceeds. Per the
-- assignment contract it is deferred and payable within one year
-- after funding, so it will be met by royalty income or a
-- subsequent round. Every answer that called it the largest use
-- of proceeds is corrected here.
--
-- Answers updated: capital_seeking, use_of_funds, deal_terms,
-- valuation_rationale, risks_mitigations, ip_portfolio,
-- milestones, growth_barriers, cost_structure.
--
-- Run AFTER seed_ctan_other_and_overview.sql and the three
-- fix_ctan_ip_disclosure files. This one is authoritative.
--
-- Rerun-safe. Supabase SQL Editor safe: self-contained statements,
-- no apostrophes or semicolons inside string literals,
-- no standalone SQL keywords inside string literals.
-- ============================================================


-- ------------------------------------------------------------
-- 1. capital_seeking
-- ------------------------------------------------------------
UPDATE app.answer_library
SET body_en = '100000',
    body_ko = '100000 - 이번 엔젤 라운드는 티슈 테스트 자금 10만 달러만 조달',
    updated_at = now()
WHERE answer_key = 'capital_seeking' AND variant = 'short';


-- ------------------------------------------------------------
-- 2. use_of_funds
-- ------------------------------------------------------------
UPDATE app.answer_library
SET body_en = 'The entire 100,000 USD funds one thing: an independent FCC validation for tissue at a US national paper laboratory. That single test converts our Korean commercial data to US data generated by a neutral American institution, and on completion the laboratory introduces us directly to the major US tissue manufacturers. Tissue is a category that has never used any filler, so this is the milestone that opens a new market rather than a share of an existing one. Breakdown: approximately 85,000 USD laboratory fees, sample preparation and shipping, and analysis. Approximately 15,000 USD travel and technical support during the trial. We are deliberately not raising more than the test requires. The 500,000 USD consideration for assigning the remaining patents is contractually deferred, payable within one year after funding, and will be met by royalty income or a subsequent round rather than by these proceeds. After the tissue data exists, we expect to raise a larger priced round at a valuation the data supports.',
    body_ko = '10만 달러 전액을 미국 국립 제지연구소의 독립 티슈 검증에 투입. 특허 이전 대가 50만 달러는 계약상 투자 유치 후 1년 내 지급이며 이번 자금으로 지출하지 않음',
    target_length = 1000, updated_at = now()
WHERE answer_key = 'use_of_funds' AND variant = 'short';


-- ------------------------------------------------------------
-- 3. deal_terms
-- ------------------------------------------------------------
UPDATE app.answer_library
SET body_en = 'Post-money SAFE, 100,000 USD round size, dedicated entirely to an independent tissue validation at a US national paper laboratory. Valuation cap 10,000,000 USD post-money, 20 percent discount, investor receives whichever is more favorable. Most favored nation clause for early investors. Terms are negotiable with a lead investor. The cap table is clean: 8,500,000 founder common shares issued, no preferred stock, options, warrants, notes or other convertible securities outstanding, and 15 percent of the fully diluted equity authorized and unissued for financings. We are raising only what the test requires, and we expect to raise a larger priced round once the US tissue data is in hand and can support a valuation. Royalty income is expected to fund operations after launch.',
    body_ko = 'post-money SAFE, 라운드 10만 달러, 캡 1000만 달러, 할인 20퍼센트, MFN. 법률 자문 아님 - 변호사 검토 필요',
    target_length = 800, updated_at = now()
WHERE answer_key = 'deal_terms' AND variant = 'short';


-- ------------------------------------------------------------
-- 4. valuation_rationale
-- ------------------------------------------------------------
UPDATE app.answer_library
SET body_en = 'We are not pricing the company in this round. We are raising 100,000 USD on a post-money SAFE with a 10,000,000 USD valuation cap and a 20 percent discount, so the price is set at the next priced round once the independent US tissue validation is complete. Raising only what the test requires means investors are funding a specific milestone rather than a runway. The cap is anchored on assets already in hand: a confirmed 9,000-ton order executing at 350 USD per ton with royalty terms approved at executive level and the definitive agreement under documentation, price validation at 250-350 USD per ton by a major mill against wood pulp at 600-800, a portfolio of 5 granted Korean patents and 7 applications across KR, PCT and US, and two peer-reviewed ACS papers co-authored by our CTO that recently served as the blocking prior art that defeated a competitor patent filing. The US application is assigned to Marinebio Group, Inc. The granted Korean patents remain with an affiliate under common ownership, their assignment consideration is contractually deferred for one year after funding, and an exclusive worldwide license granted by the affiliate is being documented as interim cover. Our validated royalty track projects 22.4M USD of Year-3 royalty, and royalty streams are near-pure margin, typically trading at 5-15x. A 10,000,000 USD cap therefore prices early angels at a substantial discount to what the validated track alone implies, which is the compensation owed to investors who move before the US data exists. Tissue, packaging and wallpaper revenue are excluded entirely.',
    target_length = 1500, updated_at = now()
WHERE answer_key = 'valuation_rationale' AND variant = 'short';


-- ------------------------------------------------------------
-- 5. ip_portfolio - correct the use-of-proceeds sentence
-- ------------------------------------------------------------
UPDATE app.answer_library
SET body_en = 'OWNERSHIP STATUS, stated plainly. Marinebio Group, Inc. currently holds one patent asset: the US application US 19/396,332, which has been assigned to it. Consideration for that assignment is unpaid and is contractually deferred, payable within one year after this financing is raised. The 5 granted patents are Korean patents registered to Marinepad, a Korean affiliate under common ownership and control - the same individual is the representative and principal shareholder of both companies. The PCT and Korean applications also remain with Marinepad. Korean patents are enforceable in Korea only. The NDA governing the license negotiation with the global filler producer was signed by Marinebio Group, Inc. and designates it as the party to receive license and royalty payments, with Marinepad identified as an affiliated company, so the commercial counterparty recognises the US entity as the licensor for the global business. The 500,000 USD consideration for assigning the remaining portfolio is not funded by this round, which is dedicated entirely to the US tissue validation. It will be met by royalty income or a subsequent round within the contractual one-year window. An exclusive worldwide license granted by Marinepad to Marinebio Group, Inc., with sublicensing rights, is being documented as interim cover until assignment completes.

GRANTED PATENTS - Korea, KIPO, 5 total, registered to Marinepad, enforceable in Korea.
KR 10-1510313 (2015) Preparation method of filler and the paper containing the filler thereby.
KR 10-1535522 (2015) Preparation method of surface-coated filler for paper manufacture and paper containing the same.
KR 10-1742962 (2017) Preparation method of filler using micro-cellulose and calcium compound and paper containing filler prepared by the same.
KR 10-1910649 (2018) Preparation method of filler containing cellulose and the paper containing the filler thereby.
KR 10-2790098 (2025) Method for preparing calcium carbonate filler using crustacea shell and paper containing the calcium carbonate filler.
Related granted: KR 10-2887327 chitin nanofiber, registered to Marinepad.

PENDING APPLICATIONS - 7 total. Preparation method of paper filler using mixed solution of organic fiber and inorganic compound and use thereof.
US 19/396,332 USPTO - assigned to Marinebio Group, Inc.
KR 10-2023-0092212 Korea - Marinepad.
KR 2024/009859 PCT - Marinepad.
National phase entries planned or filed in EU, Japan, China, India and Indonesia.

THIRD-PARTY SUBMISSIONS filed by us: USPTO 18/909,232 and the corresponding EPO application, both citing our own peer-reviewed prior art to block a competitor patent family.

PATENT LICENSES. No executed patent license has been granted to any third party to date. A license and royalty agreement covering the confirmed 9,000-ton order has been approved at executive level by the counterparty and is being documented, naming Marinebio Group, Inc. as the payee.

COPYRIGHTS AND COPYRIGHT LICENSES. None held and none granted. Our two ACS journal articles are published under the publisher standard terms and function as prior art we can cite rather than as licensed assets.

CERTIFICATION. Korea NET New Excellent Technology certificate 2023-0010, valid 2023 to 2028. Certificate holder to be confirmed.',
    target_length = 3000, updated_at = now()
WHERE answer_key = 'ip_portfolio' AND variant = 'short';


-- ------------------------------------------------------------
-- 6. risks_mitigations
-- ------------------------------------------------------------
UPDATE app.answer_library
SET body_en = 'IP is held across two affiliated entities. Marinebio Group, Inc. holds the US patent application. The 5 granted Korean patents and the PCT and Korean applications remain registered to Marinepad, an affiliate under common ownership, and the assignment consideration of 500,000 USD is contractually deferred, payable within one year after funding. Because the confirmed 9,000-ton order is supplied in Korea, the patents underpinning that royalty are the Korean ones, so today the US entity is the contractual payee rather than the owner of those patents. Mitigation: the same individual is representative and principal shareholder of both companies, so there is no adverse counterparty. The NDA with the global filler producer was signed by Marinebio Group, Inc. and names it as payee. An exclusive worldwide license granted by Marinepad to Marinebio Group, Inc., with sublicensing rights, is being documented as interim cover, and we are prepared to make completion of the assignment a condition of a later priced round. The US application, which governs the US tissue track this round funds, is already assigned to the US entity. Contract documentation. The license and royalty agreement covering the 9,000-ton order has executive approval and is being documented. Mitigation: the order is already in physical supply and documentation is being executed now. Validation is Korean, buyers are American. Mitigation: the US national-laboratory test funded by this round produces US data and ends in direct introductions to US tissue makers. Licensee concentration - confirmed volume runs through one producer. Mitigation: a second global producer is engaged under NDA and supply contracts run 10-15 years. Adoption pace - the paper industry is conservative and mills qualify materials slowly. Mitigation: FCC requires no new equipment and is sold by suppliers the mills already buy, removing the two biggest switching costs. Design-around risk. Mitigation: patents covering fiber size, structure and additives, our own published science as prior art, and an FCC network structure provable in finished paper under a standard SEM image. Key-person depth - the company is founder-led in the US. Mitigation: we are filling advisory seats through the Austin startup ecosystem rather than with cash, and the CTO and CPO anchor technical continuity.',
    target_length = 2300, updated_at = now()
WHERE answer_key = 'risks_mitigations' AND variant = 'short';


-- ------------------------------------------------------------
-- 7. milestones
-- ------------------------------------------------------------
UPDATE app.answer_library
SET body_en = 'Q3 2026 - close the 100,000 USD SAFE round and start independent FCC tissue validation at a US national paper laboratory. Q4 2026 - complete the laboratory testing, obtain the written report, and receive the laboratory introductions to major US tissue manufacturers. Q4 2026 - execute the definitive license and royalty agreement covering the confirmed 9,000-ton order, and recognise first royalty revenue as supply ramps. Q4 2026 - complete the exclusive interim license covering the Korean granted patents. H1 2027 - sign the first tissue trial with a US manufacturer, and convert approximately 10,000 tons in motion to a second confirmed order. H1 2027 - raise a priced round supported by the US data, and complete the patent assignment inside the contractual one-year window. 2027 - reach the 0.29M-ton Year-1 royalty volume on the validated track. Measurable gates: laboratory report issued, license agreement executed, first royalty payment received, tissue trial agreement signed.',
    target_length = 1000, updated_at = now()
WHERE answer_key = 'milestones' AND variant = 'short';


-- ------------------------------------------------------------
-- 8. growth_barriers
-- ------------------------------------------------------------
UPDATE app.answer_library
SET body_en = 'Three things, each with a mitigation. First, validation localization: our commercial proof is Korean mill data, and conservative US buyers want US data. The independent US national-laboratory test funded by this round removes exactly that barrier and ends with direct introductions to US tissue makers. That is why we are raising only what the test costs. Second, partner-paced rollout: the royalty model scales through large licensees, so adoption speed partly depends on their internal decisions. Mitigated by long-term volume contracts and by the fact that FCC gives producers new revenue instead of cannibalizing existing lines. Third, team bandwidth: the US commercial motion is founder-led today. We are filling advisory seats through the Austin startup ecosystem rather than with cash, and the CTO and CPO anchor technical execution. The paper industry moves slowly - but that same conservatism locks FCC in once it is specified at a mill.',
    target_length = 950, updated_at = now()
WHERE answer_key = 'growth_barriers' AND variant = 'short';


-- ------------------------------------------------------------
-- 9. cost_structure
-- ------------------------------------------------------------
UPDATE app.answer_library
SET body_en = 'We are asset-light: no plants, no inventory, no meaningful hosting - production and distribution run inside licensee plants at their cost. Our cost base is small and mostly fixed: independent testing and validation, patent prosecution and maintenance, and lean operations covering founder time, legal and business development travel. This round is allocated entirely to independent US validation, roughly 85 percent laboratory fees and analysis and 15 percent travel and technical support. The 500,000 USD assignment consideration for the remaining patents is contractually deferred for one year after funding and is not a cost of these proceeds. Customer acquisition cost is business development and technical validation rather than paid marketing, and the variable cost of an incremental royalty dollar is near zero, which is why royalties are near-pure margin.',
    target_length = 900, updated_at = now()
WHERE answer_key = 'cost_structure' AND variant = 'short';


-- ------------------------------------------------------------
-- 10. Push corrected text to bound snapshots, reset is_copied
-- ------------------------------------------------------------
UPDATE app.application_field_answers fa
SET final_text = al.body_en,
    is_copied = false,
    updated_at = now()
FROM app.answer_library al
WHERE fa.answer_id = al.id
  AND al.variant = 'short'
  AND al.answer_key IN (
    'capital_seeking','use_of_funds','deal_terms','valuation_rationale',
    'risks_mitigations','ip_portfolio','milestones','growth_barriers','cost_structure'
  );


-- Verify
SELECT seq, label, field_state, char_count, is_copied
FROM app.v_application_field_status
WHERE form_url LIKE '%dealum.com%'
  AND seq IN (603, 604, 711, 714, 719, 720, 803, 804, 901)
ORDER BY seq;
